# Spec file for the automated deployment

version: 0.2

phases:
  install:
    commands:
      - echo Current working directory - $PWD
      - echo 'Spinning up environment - Inside'
      # download the core dependencies
      - echo 'Installing the HATS dependencies'
      # install node lts
      - echo 'Installing Node...'
      - curl -fsSL https://deb.nodesource.com/setup_16.x | bash -
      - apt install -y nodejs
  pre_build:
    commands:
      # change to project root
      - echo Current working directory - $PWD
      - cd Frontend/hats-search/
      - echo current directory
      - pwd
      # install dependencies
      - echo 'Installing dependencies...'
      - npm i
  build:
    commands:
      - echo Current working directory - $PWD
      # Add the test commands
      # build
      - echo current directory
      - pwd
      - echo 'Starting build process...'
      - npm run build
      - echo 'Build finished...'
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: build